### ISSUE TITLE
Experiment robustness of Conq localization when minor changes to the environment occur

### ISSUE THREAD

**Issue by skwirskj** [UM-ARM-Lab/conq_python#16]

**Comment by dcolli23** [comment]
I appreciate the usage of the GitHub board and issue tracking! Thanks for taking the initiative on this

**Comment by skwirskj** [comment]
Going to close since I tested this and saw the robot flinch somewhat when things were moved around. Stanley and I also saw the robot get confused where it was during tool retrieval demo since a chair was moved by another student in the scene.
