### ISSUE TITLE
Explore using UM-GPT for Semantic Waypoint Generation

### ISSUE THREAD

**Issue by skwirskj** [UM-ARM-Lab/conq_python#23]
- Look into using https://umgpt.umich.edu/maizey to create custom API where you could ask "Where should I put the shears" and have it respond with some waypoint or location in our map
- Further Flesh out the system/design

**Comment by Saketspradhan** [comment]
<img width="606" alt="Screenshot 2024-02-03 at 1 06 30 AM" src="https://github.com/UM-ARM-Lab/conq_python/assets/65219413/7c905b8b-4bc1-4f90-870a-5427f6add945">
@dcolli23 @skwirskj This is what they replied to the ticket raised, right? Will we be considering it sometime?

**Comment by Saketspradhan** [comment]
Guys, do y'all want to wait for the UM-GPT ToolKit access or should we start prototyping with the ChatGPT API itself? ChatGPT's API is pretty well documented and organized, should be a good starting point if UM-GPT's gonna take a while 
@dcolli23 @skwirskj @JemuelStanley47

**Comment by skwirskj** [comment]
@Saketspradhan was able to integrate chat gpt and we will pivot to um gpt once ready
