### ISSUE TITLE
Object Locations in Map Class

### ISSUE THREAD

**Issue by skwirskj** [UM-ARM-Lab/conq_python#24]
- Create a class to represent an object, such as a hammer, tool, etc. in the map
- Find how waypoints are designated in Spot i.e. pose, lat/long, etc. specifically for the `navigateTo` function

**Comment by dcolli23** [comment]
You may want to take a look at the `MapAnchored` class that I've written for the replay with map data. That may give you some insight on how maps are structured

**Comment by skwirskj** [comment]
Going to use the built-in waypoint proto/class since it is exactly what Spot expects and there is an `annotations` field where we can give the waypoint a human-readable name such as "garage" "shed" "shovel" etc.
